### ISSUE TITLE
Documentation or example of calling a Contract method?

### ISSUE THREAD

**Issue by luca992** [icerockdev/moko-web3#107]
I'm trying to simply get the name of a ERC721 contract.

```
    val apiKey = "..."
    val web3: Web3 = Web3("https://mainnet.infura.io/v3/$apiKey")
    val smartContractString = "..."
    val smartContractJson = Json.parseToJsonElement(smartContractString).jsonObject
    val networkData : JsonObject = smartContractJson["networks"]!!.jsonObject[networkId]?.jsonObject!!
    val adr  = networkData["address"]?.jsonPrimitive?.content!!
    val abis = smartContractJson["abi"]!!.jsonArray

    val sc = SmartContract(web3, ContractAddress(adr), abis))
    
    val names = sc.read("name", emptyList())
            { l ->
                l.map {
                    it.toString()
                }
            }
    val contractName = names[0]
        
```
First of all I'm not really sure what a valid mapper would look like? Or why it would return multiple values from one read. Do you have any examples? And second, `names` ends up being empty, so nothing is being returned? Any help on the correct way to call a contract method would be appreciated.

**Comment by y9san9** [comment]
This process is kinda unclear for now. The result is List<Any?> since "outputs" of a smart contract method may contain multiple types. 

<img width="332" alt="Снимок экрана 2022-02-21 в 09 38 39" src="https://user-images.githubusercontent.com/46930374/154902222-0bc01c06-df47-4b84-b300-2d499a41d4fd.png">

They automatically decoded using ABI, but we can't know the returning types in compile time, so we have to cast it manually. 

```kotlin
class NftContract(
    private val wrapped: SmartContract
) {
    fun name() = wrapped.read(
        method = "name",
        params = emptyList()
    ) { (name) → name as String }
}
```

**Comment by y9san9** [comment]
You should know underlying types for encoders/decoders to do mappings. That's kinda internal thing for now and it's not documented properly. Example of mappings:

bytes* → ByteArray
uint* → BigInt
address → BigInt
string → String

**Comment by luca992** [comment]
Okay, got it. Thanks! However, now I'm getting the error: 

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class kotlin.collections.EmptyList cannot be cast to class java.lang.String (kotlin.collections.EmptyList is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at web3.eth.CommonContract$getName$2$name$1.invoke(CommonContract.kt:12)
	at web3.eth.CommonContract$getName$2$name$1.invoke(CommonContract.kt:12)
	at dev.icerock.moko.web3.contract.SmartContract$makeAbiDeserializer$1.deserialize(SmartContract.kt:50)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
	at dev.icerock.moko.web3.Web3.typed(Web3.kt:106)
	at dev.icerock.moko.web3.Web3.processResponse(Web3.kt:124)
	at dev.icerock.moko.web3.Web3.executeBatch(Web3.kt:93)
	at dev.icerock.moko.web3.Web3$executeBatch$1.invokeSuspend(Web3.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Note, I'm doing this on JVM not android. I rebuilt the project and replaced the OkHttp ktor engine with the CIO engine. Not sure if that would matter?

**Comment by luca992** [comment]
Got it working!

```
class NftContract(
    private val wrapped: SmartContract
) {
    suspend fun name() = wrapped.read(
        method = "name",
        params = emptyList()
    ) { name -> name as List<String> }[0]
}
```

is what I had to use.

**Comment by luca992** [comment]
@y9san9

**Comment by luca992** [comment]
Basically I'm returning an array of a struct. Is that able to be parsed at the moment? Or was that not implemented here? Seem's like that's a newer feature introduced in solidity 0.8.0

**Comment by y9san9** [comment]
That should work, but how the library would know what is `AllTokensResponse`?

**Comment by y9san9** [comment]
But maybe it don't implemented, hard to say

**Comment by y9san9** [comment]
The implementation of array[] type should work for any type

**Comment by luca992** [comment]
If I leave it as a mapper with List<Any?>

And comment out the require that is failing:
```
        require(callData.size >= headSize) {
            "Call data size should be at least equals params count multiplied by 32, " +
                    "because it should be the head size." +
                    "Param types: $paramTypes; CallData: ${callData.toHex()}"
        }
```

This the result is definitely not correct
![image](https://user-images.githubusercontent.com/4157455/155413982-23431e98-9aa7-4c55-917d-dc87d12ee521.png)

**Comment by y9san9** [comment]
Give please the calldata you are trying to encode, I will investigate it soon

**Comment by luca992** [comment]
this is the contract.

```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.1;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/Counters.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract SmartContract is ERC721, Ownable  {
    using Counters for Counters.Counter;
    // using Strings for uint256;
    Counters.Counter _tokenIds;
    mapping(uint256 => string) _tokenURIs;

    struct RenderToken {
        uint256 id;
        string uri;
    }

    constructor() ERC721("Smart Contract", "SC") {}

    function _setTokenURI(uint256 tokenId, string memory _tokenURI) internal {
        _tokenURIs[tokenId] = _tokenURI;
    }

    function tokenURI(uint256 tokenId) public view virtual override returns(string memory) {
        require(_exists(tokenId));
        string memory _tokenURI = _tokenURIs[tokenId];
        return _tokenURI;
    }

    function getAllTokens() public view returns(RenderToken[] memory) {
        uint256 latestId = _tokenIds.current();
        RenderToken[] memory res = new RenderToken[](latestId);
        for(uint256 i = 0; i < latestId; i++) {
            if(_exists(i)) {
                string memory uri = tokenURI(i);
                res[i] = RenderToken(i, uri);
            }
        }
        return res;
    }

    function mint(address recipient, string memory uri) public returns(uint256) {
        uint256 newId = _tokenIds.current();
        _mint(recipient, newId);
        _setTokenURI(newId, uri);
        _tokenIds.increment();
        return newId;
    }

}
```

This is a response after minting one token that needs to be decoded.

```
{"id":0,"jsonrpc":"2.0","result":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004a68747470733a2f2f697066732e696e667572612e696f2f697066732f516d5937416d76756b756938344a675072694435346b46556b616f3765586b4b6d357a4848316e794e674c356f5900000000000000000000000000000000000000000000"}
```

That's what you need right?

**Comment by y9san9** [comment]
Yep thank you

**Comment by y9san9** [comment]
Working on this now in symbiosis-finance/moko-web3
